// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CFG.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GtirbSharp.proto
{

    [global::ProtoBuf.ProtoContract()]
    internal partial class EdgeLabel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension? __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"conditional")]
        public bool Conditional { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"direct")]
        public bool Direct { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        public EdgeType Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    internal partial class Edge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension? __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"source_uuid")]
        public byte[]? SourceUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_uuid")]
        public byte[]? TargetUuid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"label")]
        public EdgeLabel? Label { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"CFG")]
    internal partial class Cfg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension? __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"vertices")]
        public global::System.Collections.Generic.List<byte[]> Vertices { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(2, Name = @"edges")]
        public global::System.Collections.Generic.List<Edge> Edges { get; } = new global::System.Collections.Generic.List<Edge>();

    }

    [global::ProtoBuf.ProtoContract()]
    internal enum EdgeType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"Type_Branch")]
        TypeBranch = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"Type_Call")]
        TypeCall = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Type_Fallthrough")]
        TypeFallthrough = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"Type_Return")]
        TypeReturn = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"Type_Syscall")]
        TypeSyscall = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"Type_Sysret")]
        TypeSysret = 5,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
